plugins:
  - jekyll-relative-links
  - jekyll-titles-from-headings
relative_links:
  enabled: true
  collections: true
titles_from_headings:
  enabled: true
  strip_title: false
  collections: false
github:
  repository_url: https://pawwol90.github.io
  is_project_page: false
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
theme: jekyll-theme-hacker
title: Paweł Wołoszyn
description: Witam na mojej stronie github!
